---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: srenix-website
resources:
  - namespace.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - kong-redirect.yaml
commonLabels:
  app.kubernetes.io/part-of: srenix
